<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>C:\Users\stigz\source\repos\0.MyCode\NET\RommStar\src\RommStar.Core\bin</BaseOutputPath>
    <ApplicationIcon>rommIcon64px.ico</ApplicationIcon>
    <Configurations>Debug;Release;Patch;Major</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="rommIcon64px.ico" />
  </ItemGroup>

</Project>
