<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

	<PropertyGroup>
		<TargetFramework>net9.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="UI\Rommstar\**" />
		<EmbeddedResource Remove="UI\Rommstar\**" />
		<None Remove="UI\Rommstar\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Monikers.imagemanifest" />
	  <None Remove="Resources\rommIcon64px.ico" />
	  <None Remove="Resources\rommIcon64px.png" />
	</ItemGroup>

	<ItemGroup>
	  <content Include="Monikers.imagemanifest">
	    <IncludeInVSIX>true</IncludeInVSIX>
	  </content>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="System.Drawing.Common" Version="9.0.0">
			<HintPath>..\..\lib\launchbox\System.Drawing.Common.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Unbroken.LaunchBox.Plugins">
			<HintPath>..\..\lib\launchbox\Unbroken.LaunchBox.Plugins.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.DependencyInjection">
			<HintPath>..\..\lib\launchbox\Microsoft.Extensions.DependencyInjection.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
			<HintPath>..\..\lib\launchbox\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="System.Private.Windows.Core">
			<HintPath>..\..\lib\launchbox\System.Private.Windows.Core.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2">
			<Private>true</Private>
		</PackageReference>
		<PackageReference Include="iNKORE.UI.WPF" Version="1.2.8" ExcludeAssets="runtime" />
		<PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.10.2.1" ExcludeAssets="runtime" />
	</ItemGroup>

	<Target Name="CopyAndDisguiseAssemblies" AfterTargets="CopyFilesToOutputDirectory">
		<ItemGroup>
			<TargetDlls Include="@(ReferencePath)" Condition="'%(FileName)' == 'iNKORE.UI.WPF' or '%(FileName)' == 'iNKORE.UI.WPF.Modern' or '%(FileName)' == 'iNKORE.UI.WPF.Modern.Controls'" />
		</ItemGroup>
		<Copy SourceFiles="@(TargetDlls)" DestinationFiles="@(TargetDlls->'$(TargetDir)%(FileName).dll.dep')" SkipUnchangedFiles="true" />
	</Target>

	<ItemGroup>
	  <Resource Include="Resources\rommIcon64px.ico" />
	  <Resource Include="Resources\rommIcon64px.png" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<Compile Update="Properties\Settings.Designer.cs">
		  <DesignTimeSharedInput>True</DesignTimeSharedInput>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Properties\Settings.settings">
	    <Generator>SettingsSingleFileGenerator</Generator>
	    <LastGenOutput>Settings.Designer.cs</LastGenOutput>
	  </None>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="call &quot;$(SolutionDir)\build\scripts\moveDebugBuild.bat&quot; &quot;$(ConfigurationName)&quot; &quot;$(SolutionDir)&quot; &quot;C:\Users\stigz\LaunchboxDEV\LaunchBox\Plugins\RommStar&quot; &quot;src\RommStar.Core\bin\Debug\net9.0-windows&quot;" />
	</Target>

</Project>