<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

	<PropertyGroup>
		<TargetFramework>net9.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="UI\Rommstar\**" />
	  <EmbeddedResource Remove="UI\Rommstar\**" />
	  <None Remove="UI\Rommstar\**" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="System.Drawing.Common"  Version="9.0.0">
			<HintPath>..\..\lib\launchbox\System.Drawing.Common.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Unbroken.LaunchBox.Plugins">
			<HintPath>..\..\lib\launchbox\Unbroken.LaunchBox.Plugins.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Unbroken.LaunchBox.Plugins">
			<HintPath>..\..\lib\launchbox\Microsoft.Extensions.DependencyInjection.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
			<HintPath>..\..\lib\launchbox\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="System.Private.Windows.Core">
			<HintPath>..\..\lib\launchbox\System.Private.Windows.Core.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Resources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="UI\ViewModels\" />
	  <Folder Include="UI\Views\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="AdonisUI" Version="1.17.1" />
	  <PackageReference Include="AdonisUI.ClassicTheme" Version="1.17.1" />
	  <!-- Ensure the project explicitly depends on System.Drawing.Common v9 so NuGet resolves v9 instead of the transitive 4.6.0 -->
	  <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="call &quot;$(SolutionDir)\build\scripts\moveDebugBuild.bat&quot; &quot;$(ConfigurationName)&quot; &quot;$(SolutionDir)&quot; &quot;C:\Users\stigz\LaunchboxDEV\LaunchBox\Plugins\RommStar&quot; &quot;src\RommStar.Core\bin\Debug\net9.0&quot;" />
	</Target>

</Project>
