<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RommStar.Core\RommStar.Core.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="System.Drawing.Common">
			<HintPath>..\..\lib\launchbox\System.Drawing.Common.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Unbroken.LaunchBox.Plugins">
			<HintPath>..\..\lib\launchbox\Unbroken.LaunchBox.Plugins.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Unbroken.LaunchBox.Plugins">
			<HintPath>..\..\lib\launchbox\Microsoft.Extensions.DependencyInjection.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
			<HintPath>..\..\lib\launchbox\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="System.Private.Windows.Core">
			<HintPath>..\..\lib\launchbox\System.Private.Windows.Core.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="call &quot;$(SolutionDir)\build\scripts\moveDebugBuild.bat&quot; &quot;$(ConfigurationName)&quot; &quot;$(SolutionDir)&quot; &quot;C:\Users\stigz\LaunchboxDEV\LaunchBox\Plugins\RommStar&quot; &quot;src\RommStar.UI\bin\Debug\net9.0&quot;" />
	</Target>


</Project>
